/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  openApiSidebar: [
    {
      type: "category",
      label: "Nopaper API",
      link: {
        type: "generated-index",
        title: "Nopaper API",
        description:
          "Документация по интеграции Nopaper API",
        slug: "/nopaper-api"
      },
      // @ts-ignore
      items: require("./docs/nopaper-api/sidebar.js")
    }
  ],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Сценарии",
      link: {
        type: "generated-index",
        title: "Все сценарии интеграции",
        description:
            "Инструкции по использованию Nopaper API для партнёров",
        slug: "/scenarios"
      },
      // @ts-ignore
      items: require("./docs/scenarios/sidebar.js")
    }
  ],

};

module.exports = sidebars;
